routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home');

Auth::routes();

Route::get('/registerInstitute', 'UserController@registerInstitute')->name('registerInstitute');

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/students', 'HomeController@student')->name('student');
Route::get('/schools', 'HomeController@school')->name('school');
Route::get('/recruiters', 'HomeController@recruiter')->name('recruiter');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/study-destination', 'HomeController@studyDestination')->name('study-destination');
Route::post('/study-search-result', 'HomeController@studySearchResult')->name('study-search-result');
Route::get('/all-program/{id}', 'HomeController@program')->name('all-program');
Route::get('/country-details', 'HomeController@countryDetails')->name('country-details');


Route::resource('school-form', 'SchoolInfoController');

Route::post('user/storeSchool', 'UserController@storeSchool')->name('storeSchool');
Route::resource('user', 'UserController');

Route::middleware('auth')->group(function () {
    Route::group([ 'middleware' => 'student'], function() {
    });
        Route::get('student/show-profile/{id}', 'StudentController@showProfile')->name('students-form.showProfile');
        Route::put('program/apply/{id}/{student_id}', 'ProgramController@programApply')->name('program.apply');
        Route::resource('program', 'ProgramController');
        Route::get('/dashboard/school-index', 'AllusertableController@schoolIndex')->name('school.index');
        Route::get('get-school-list', 'AllusertableController@schoolList')->name('get-school-list');

        Route::resource('students-form', 'StudentController');

    Route::group([ 'middleware' => 'admin'], function() {


    });

    Route::get('get-user-list', 'AllusertableController@userList')->name('get-user-list');
    Route::get('/dashboard/allusrIndex/{role_id}', 'AllusertableController@index')->name('alluser.index');
    Route::get('get-student-list', 'AllusertableController@studentList')->name('get-student-list');
    Route::get('/dashboard/student-index', 'AllusertableController@studentIndex')->name('student.index');
    Route::get('get-recruiter-list', 'AllusertableController@recruiterList')->name('get-recruiter-list');
    Route::get('/dashboard/recruiter-index', 'AllusertableController@recruiterIndex')->name('recruiter.index');
    Route::get('get-supervisor-list', 'AllusertableController@supervisorList')->name('get-supervisor-list');
    Route::get('/dashboard/supervisor-index', 'AllusertableController@supervisorIndex')->name('supervisor1.index');

    Route::resource('supervisor', 'SupervisorController');

    Route::resource('country', 'CountryController');
    Route::get('get-country-list', 'CountryController@getAllCountry')->name('get-country-list');
    Route::post('get-country-info', 'CountryController@getCountryInfo')->name('get-country-info');

    Route::put('dashboard/allusrIndex/user-approval/{id}', 'StudentController@userApproval')->name('user.approval');
    Route::put('student-form/assign-supervisor/{id}', 'StudentController@assignSupervisor')->name('student-form.assignSupervisor');
    Route::resource('recruiters-form', 'RecruiterController');
    Route::get('program-recruiter-index/{id}', 'AllusertableController@programRecruiter')->name('programRecruiter.index');

    Route::get('get-studentRecruiter-list', 'RecruiterController@studentListForRecruiter')->name('get-studentRecruiter-list');
    Route::get('get-studentSupervisor-list', 'SupervisorController@studentListForSupervisor')->name('get-studentSupervisor-list');


    Route::get('campus-add', 'CampusController@campusAdd')->name('addcampus.index');
    Route::get('program-add', 'ProgramController@programAdd')->name('addprogram.index');
    Route::get('program/forall/{id}', 'ProgramController@showforall')->name('program.showforall');

    Route::resource('campus', 'CampusController');
    Route::resource('program', 'ProgramController');
    Route::resource('comment', 'CommentController');

    Route::put('program/apply/{id}/{student_id}', 'ProgramController@programApply')->name('program.apply');
    Route::get('/dashboard/allprogram-index/{id}', 'AllusertableController@programIndex')->name('allprogram.index');

    Route::put('program/assign-status/{id}/{student_id}', 'ProgramController@assignStatus')->name('program.assign-status');





    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');




    Route::get('manage/{id}', 'DashboardController@userManage')->name('user.manage');

    Route::get('/home-components', 'HomeController@homeComponents')->name('home-components');

    Route::resource('role', 'RoleController');

    Route::resource('merchants', 'MerchantController');
    Route::get('merchant-requests', 'MerchantController@merchantRequest')->name('merchant-requests');
    Route::get('merchant-inactive', 'MerchantController@merchantInactive')->name('merchants.inactive');
    Route::get('get-merchants-admin', 'MerchantController@getIndexAdmin')->name('get-merchants-admin');
    Route::get('merchant-active/{id}', 'MerchantController@merchantActive')->name('merchant.active');

    Route::resource('special-merchants', 'SpecialMerchantController');

    Route::resource('customers', 'CustomerController');
    Route::get('customers-requests', 'CustomerController@merchantRequest')->name('customers-requests');
    Route::get('customers-active/{id}', 'CustomerController@merchantActive')->name('customers.active');

    Route::resource('admin-services', 'ServiceController');

    Route::resource('admin-client', 'ClientController');
    Route::resource('authority-team', 'AuthorityTeamController');

    Route::resource('admin-inter-city-rates', 'InterCityRateController');
    Route::resource('admin-rate-info', 'AddRateInfoController');

    Route::resource('admin-about', 'AboutUsController');
    Route::resource('admin-about-card', 'AboutUsCardController');

    Route::resource('districts', 'DistrictController');

    Route::resource('areas', 'AreaController');



    Route::resource('deliveries', 'DeliveryController');
    Route::get('print/delivery-info/{id}', 'DeliveryController@printInfoDelivery')->name('deliveries.info.print');
    Route::get('print/pickup-info/{id}', 'DeliveryController@printInfoPickup')->name('deliveries.pickup.print');
    Route::get('deliveries-admin', 'DeliveryController@indexAdmin')->name('deliveries-admin');
    Route::get('all-deliveries-admin', 'DeliveryController@indexAll')->name('all.deliveries');
    Route::get('get-deliveries-admin', 'DeliveryController@getIndexAdmin')->name('get-deliveries-admin');
    Route::get('get-all-deliveries-admin', 'DeliveryController@getAll')->name('get-all-deliveries-admin');
    Route::post('manage-deliveries-admin', 'DeliveryController@manageDelivery')->name('manage-deliveries-admin');
    Route::post('get-delivery-info', 'DeliveryController@getDeliveryInfo')->name('get-delivery-info');
    Route::post('admin-delivered', 'DeliveryController@delivered')->name('admin.delivered');
    Route::post('admin-pickup', 'DeliveryController@pickup')->name('admin.pickup');
    Route::post('admin-cancel', 'DeliveryController@cancel')->name('admin.cancel');
    Route::post('admin-hold', 'DeliveryController@hold')->name('admin.hold');
    Route::post('admin-no-status', 'DeliveryController@noStatus')->name('admin.no.status');
    Route::post('admin-paid', 'DeliveryController@paid')->name('admin.paid');
    Route::post('admin-unpaid', 'DeliveryController@unPaid')->name('admin.unpaid');
    Route::post('deliveries-delete', 'DeliveryController@delete')->name('deliveries.delete');

    Route::get('admin-delivery-statuses', 'DeliveryController@statuses')->name('admin.statuses');

    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::get('get-invoices', 'InvoiceController@getInvoice')->name('get.invoices');
    Route::get('invoice/delete/{id}', 'InvoiceController@delete')->name('invoice.delete');
    Route::get('invoice/{id}', 'InvoiceController@show')->name('invoice.show');
    Route::post('delivery/invoice', 'InvoiceController@getInvoiceInfo')->name('delivery.invoice');
    Route::get('invoice/pdf-export/{id}', 'InvoiceController@export')->name('export.pdf');

    Route::resource('payment-requests', 'PaymentRequestsController');
    Route::get('get-payment-requests', 'PaymentRequestsController@getRequest');
    Route::post('admin.request.solve', 'PaymentRequestsController@solveRequest')->name('admin.request.solve');
    Route::post('admin.request.pending', 'PaymentRequestsController@pendingRequest')->name('admin.request.pending');

});

resources/views/layouts/backend/client-team/client-create-modal.blade.php
<div class="modal fade client-create" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    {{-- <div class="modal-dialog modal-lg modal-dialog-centered"> --}}
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Create Client</h5>
            <button style="color: white" type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          </div>


        <div class="modal-body">
            <form action="{{route('admin-client.store')}}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                        <label class="bmd-label-floating">Name <span style="color: red">*</span></label>
                        <input name="name" type="text" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                        <label class="bmd-label-floating">Title <span style="color: red">*</span></label>
                        <input name="title" type="text" class="form-control" required>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                        <label class="bmd-label-floating">Description <span style="color: red">*</span></label>
                        <textarea name="body" class="form-control" id="exampleFormControlTextarea1" rows="5" spellcheck="false" required></textarea>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <span>Choose file <span style="color: red">*</span></span>
                        <input name="image" style="width: 100%" type="file" required>
                    </div>
                    </div>
                    <br>
                    <button type="submit" class="btn btn-primary pull-right">Create</button>
                    <div class="clearfix"></div>
            </form>
        {{-- form End--}}

        </div>
      </div>
    </div>
  </div>

resources/views/layouts/backend/client-team/client-edit.blade.php
@extends('layouts.backend.layouts.app')
@section('content')
    <div class="container-fluid">
      <div class="row">
        {{-- <div class="col-md-8"> --}}
          <div class="card">
            <div class="card-header card-header-info">
              <h4 class="card-title">Update Client</h4>
            </div>
            <div class="card-body">
                <form action="{{ route('admin-client.update', $data->id) }}" method="POST" enctype="multipart/form-data">
                    {{ method_field('PUT') }}
                    {{ csrf_field() }}
                    <br>
                    <br>
                        <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                            <label class="bmd-label-floating">name</label>
                            <input value="{{$data->name}}" name="name" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                            <label class="bmd-label-floating">Title</label>
                            <input value="{{$data->title}}" name="title" type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-4">
                            <span>Choose file</span>
                            <input name="image" style="width: 100%" type="file">
                        </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                <label class="bmd-label-floating">Description</label>
                                <textarea name="body" class="form-control" id="exampleFormControlTextarea1" rows="5" spellcheck="false">{{$data->body}}</textarea>
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary pull-right">Update</button>
                        <a class="btn btn-danger pull-right" href="{{route('admin-client.index')}}">Back</a>
                        {{-- <button type="submit" class="btn btn-danger pull-right">Update</button> --}}
                        <div class="clearfix"></div>
                </form>
            </div>
          </div>
        {{-- </div> --}}
      </div>
    </div>


@endsection

resources/views/layouts/backend/client-team/delete-modal.blade.php
<div class="modal fade" tabindex="-1" role="dialog" id="confirm" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <p>Are you sure you want to delete this?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger" id="delete-btn">Delete</button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/backend/client-team/index.blade.php
@extends('layouts.backend.layouts.app')
@section('content')
    <div class="container-fluid">
      <div class="row">
        {{-- <div class="col-md-8"> --}}
          <div class="card">
            @include('layouts.backend.home-component.home-component')
            <div class="card-body">
                <button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target=".client-create">Create New Client</button>
                <div class="clearfix"></div>
                <br>
                @php
                 $i = 1;
                @endphp
                <div class="table-responsive">
                <table class="table table-bordered table-hover" data-form="deleteForm">
                    <thead class="card-header-primary no-shadow">
                      <tr style="text-align: center">
                        <th scope="col">SL</th>
                        <th scope="col">Name</th>
                        <th scope="col">Title</th>
                        <th scope="col">Description</th>
                        <th scope="col">Image</th>
                        <th scope="col">Created At</th>
                        <th scope="col">Created By</th>
                        <th scope="col">Updated At</th>
                        <th scope="col">Updated By</th>
                        <th scope="col">Action</th>
                      </tr>
                    </thead>
                    <tbody>
                    @foreach ($data as $row)
                        <tr style="text-align: center">
                            <td>{{$i++}}</td>
                            <td>{{$row->name}}</td>
                            <td>{{$row->title}}</td>
                            <td>{{$row->body}}</td>
                            <td>
                                {{-- <img src="{{asset('public/clients/'.$row->image)}}" alt=""> --}}
                                <img style="height: 12em" class="img-fluid" src="{{asset('clients/'.$row->image)}}" alt="">
                            </td>
                            <td>{{$row->created_at}}</td>
                            <td>{{$row->clientCreatedBy['name']}}</td>
                            <td>{{$row->updated_at}}</td>
                            <td>{{$row->clientUpdatedBy['name']}}</td>
                            <td class="td-actions">
                                <a class="btn btn-primary btn-link" href="{{ route('admin-client.edit', $row->id) }}">
                                    <i class="material-icons">edit</i>
                                </a>

                                <form class="form-delete" action="{{ route('admin-client.destroy', $row->id) }}" method="POST">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" title="Delete" class="delete btn btn-danger btn-link">
                                        <i class="material-icons">close</i>
                                      </button>
                                </form>


                              </td>
                        </tr>
                    @endforeach
                      </tr>
                    </tbody>
                  </table>
                </div>
            </div>
          </div>
        {{-- </div> --}}
      </div>
    </div>


@include('layouts.backend.client-team.delete-modal')
@include('layouts.backend.client-team.client-create-modal')

@endsection

@push('scripts')

@endpush