routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home');

Auth::routes();

Route::get('/registerInstitute', 'UserController@registerInstitute')->name('registerInstitute');

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/students', 'HomeController@student')->name('student');
Route::get('/schools', 'HomeController@school')->name('school');
Route::get('/recruiters', 'HomeController@recruiter')->name('recruiter');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/study-destination', 'HomeController@studyDestination')->name('study-destination');
Route::post('/study-search-result', 'HomeController@studySearchResult')->name('study-search-result');
Route::get('/all-program/{id}', 'HomeController@program')->name('all-program');
Route::get('/country-details', 'HomeController@countryDetails')->name('country-details');


Route::resource('school-form', 'SchoolInfoController');

Route::post('user/storeSchool', 'UserController@storeSchool')->name('storeSchool');
Route::resource('user', 'UserController');

Route::middleware('auth')->group(function () {
    Route::group([ 'middleware' => 'student'], function() {
    });
        Route::get('student/show-profile/{id}', 'StudentController@showProfile')->name('students-form.showProfile');
        Route::put('program/apply/{id}/{student_id}', 'ProgramController@programApply')->name('program.apply');
        Route::resource('program', 'ProgramController');
        Route::get('/dashboard/school-index', 'AllusertableController@schoolIndex')->name('school.index');
        Route::get('get-school-list', 'AllusertableController@schoolList')->name('get-school-list');

        Route::resource('students-form', 'StudentController');

    Route::group([ 'middleware' => 'admin'], function() {


    });

    Route::get('get-user-list', 'AllusertableController@userList')->name('get-user-list');
    Route::get('/dashboard/allusrIndex/{role_id}', 'AllusertableController@index')->name('alluser.index');
    Route::get('get-student-list', 'AllusertableController@studentList')->name('get-student-list');
    Route::get('/dashboard/student-index', 'AllusertableController@studentIndex')->name('student.index');
    Route::get('get-recruiter-list', 'AllusertableController@recruiterList')->name('get-recruiter-list');
    Route::get('/dashboard/recruiter-index', 'AllusertableController@recruiterIndex')->name('recruiter.index');
    Route::get('get-supervisor-list', 'AllusertableController@supervisorList')->name('get-supervisor-list');
    Route::get('/dashboard/supervisor-index', 'AllusertableController@supervisorIndex')->name('supervisor1.index');

    Route::resource('supervisor', 'SupervisorController');

    Route::resource('country', 'CountryController');
    Route::get('get-country-list', 'CountryController@getAllCountry')->name('get-country-list');
    Route::post('get-country-info', 'CountryController@getCountryInfo')->name('get-country-info');

    Route::put('dashboard/allusrIndex/user-approval/{id}', 'StudentController@userApproval')->name('user.approval');
    Route::put('student-form/assign-supervisor/{id}', 'StudentController@assignSupervisor')->name('student-form.assignSupervisor');
    Route::resource('recruiters-form', 'RecruiterController');
    Route::get('program-recruiter-index/{id}', 'AllusertableController@programRecruiter')->name('programRecruiter.index');

    Route::get('get-studentRecruiter-list', 'RecruiterController@studentListForRecruiter')->name('get-studentRecruiter-list');
    Route::get('get-studentSupervisor-list', 'SupervisorController@studentListForSupervisor')->name('get-studentSupervisor-list');


    Route::get('campus-add', 'CampusController@campusAdd')->name('addcampus.index');
    Route::get('program-add', 'ProgramController@programAdd')->name('addprogram.index');
    Route::get('program/forall/{id}', 'ProgramController@showforall')->name('program.showforall');

    Route::resource('campus', 'CampusController');
    Route::resource('program', 'ProgramController');
    Route::resource('comment', 'CommentController');

    Route::put('program/apply/{id}/{student_id}', 'ProgramController@programApply')->name('program.apply');
    Route::get('/dashboard/allprogram-index/{id}', 'AllusertableController@programIndex')->name('allprogram.index');

    Route::put('program/assign-status/{id}/{student_id}', 'ProgramController@assignStatus')->name('program.assign-status');





    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');




    Route::get('manage/{id}', 'DashboardController@userManage')->name('user.manage');

    Route::get('/home-components', 'HomeController@homeComponents')->name('home-components');

    Route::resource('role', 'RoleController');

    Route::resource('merchants', 'MerchantController');
    Route::get('merchant-requests', 'MerchantController@merchantRequest')->name('merchant-requests');
    Route::get('merchant-inactive', 'MerchantController@merchantInactive')->name('merchants.inactive');
    Route::get('get-merchants-admin', 'MerchantController@getIndexAdmin')->name('get-merchants-admin');
    Route::get('merchant-active/{id}', 'MerchantController@merchantActive')->name('merchant.active');

    Route::resource('special-merchants', 'SpecialMerchantController');

    Route::resource('customers', 'CustomerController');
    Route::get('customers-requests', 'CustomerController@merchantRequest')->name('customers-requests');
    Route::get('customers-active/{id}', 'CustomerController@merchantActive')->name('customers.active');

    Route::resource('admin-services', 'ServiceController');

    Route::resource('admin-client', 'ClientController');
    Route::resource('authority-team', 'AuthorityTeamController');

    Route::resource('admin-inter-city-rates', 'InterCityRateController');
    Route::resource('admin-rate-info', 'AddRateInfoController');

    Route::resource('admin-about', 'AboutUsController');
    Route::resource('admin-about-card', 'AboutUsCardController');

    Route::resource('districts', 'DistrictController');

    Route::resource('areas', 'AreaController');



    Route::resource('deliveries', 'DeliveryController');
    Route::get('print/delivery-info/{id}', 'DeliveryController@printInfoDelivery')->name('deliveries.info.print');
    Route::get('print/pickup-info/{id}', 'DeliveryController@printInfoPickup')->name('deliveries.pickup.print');
    Route::get('deliveries-admin', 'DeliveryController@indexAdmin')->name('deliveries-admin');
    Route::get('all-deliveries-admin', 'DeliveryController@indexAll')->name('all.deliveries');
    Route::get('get-deliveries-admin', 'DeliveryController@getIndexAdmin')->name('get-deliveries-admin');
    Route::get('get-all-deliveries-admin', 'DeliveryController@getAll')->name('get-all-deliveries-admin');
    Route::post('manage-deliveries-admin', 'DeliveryController@manageDelivery')->name('manage-deliveries-admin');
    Route::post('get-delivery-info', 'DeliveryController@getDeliveryInfo')->name('get-delivery-info');
    Route::post('admin-delivered', 'DeliveryController@delivered')->name('admin.delivered');
    Route::post('admin-pickup', 'DeliveryController@pickup')->name('admin.pickup');
    Route::post('admin-cancel', 'DeliveryController@cancel')->name('admin.cancel');
    Route::post('admin-hold', 'DeliveryController@hold')->name('admin.hold');
    Route::post('admin-no-status', 'DeliveryController@noStatus')->name('admin.no.status');
    Route::post('admin-paid', 'DeliveryController@paid')->name('admin.paid');
    Route::post('admin-unpaid', 'DeliveryController@unPaid')->name('admin.unpaid');
    Route::post('deliveries-delete', 'DeliveryController@delete')->name('deliveries.delete');

    Route::get('admin-delivery-statuses', 'DeliveryController@statuses')->name('admin.statuses');

    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::get('get-invoices', 'InvoiceController@getInvoice')->name('get.invoices');
    Route::get('invoice/delete/{id}', 'InvoiceController@delete')->name('invoice.delete');
    Route::get('invoice/{id}', 'InvoiceController@show')->name('invoice.show');
    Route::post('delivery/invoice', 'InvoiceController@getInvoiceInfo')->name('delivery.invoice');
    Route::get('invoice/pdf-export/{id}', 'InvoiceController@export')->name('export.pdf');

    Route::resource('payment-requests', 'PaymentRequestsController');
    Route::get('get-payment-requests', 'PaymentRequestsController@getRequest');
    Route::post('admin.request.solve', 'PaymentRequestsController@solveRequest')->name('admin.request.solve');
    Route::post('admin.request.pending', 'PaymentRequestsController@pendingRequest')->name('admin.request.pending');

});

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;
use DB;
use App\Models\SchoolInfo;
use App\Models\Delivery;
use App\Models\role;
use App\User;
use App\Program;
use App\Student;
use App\Supervisor;
use App\Models\Recruiter;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    // After Login Components
    public function index()
    {
        if(auth()->user()->role_id==1 && auth()->user()->status==1){

            $user=User::all();
            $student=Student::orderBy('created_at', 'desc')->get();
            $recruiter=Recruiter::all();
            $supervisor=Supervisor::all();
            $school=Schoolinfo::orderBy('created_at', 'desc')->get();
            $program=Program::all();

            return view('layouts.backend.dashboard.dashboard',compact('user','student','recruiter','supervisor','school','program'));
        }

        if(auth()->user()->role_id==2 && auth()->user()->status==1){
            $student=Student::findOrFail(auth()->user()->student->id);

            return view('layouts.backend.dashboard.dashboard', compact('student'));
        }

        if(auth()->user()->role_id==3 && auth()->user()->status==1){
            $recruiter=Recruiter::findOrFail(auth()->user()->recruiter->id);

            return view('layouts.backend.dashboard.dashboard', compact('recruiter'));
        }

        if(auth()->user()->role_id==5 && auth()->user()->status==1){
            $school_student=DB::table('program_student')
            ->join('students','program_student.student_id','=','students.id')
            ->join('programs','program_student.program_id','=','programs.id')
            ->where('school_info_id',auth()->user()->school->id)

            ->get();

            $school_student=json_decode($school_student,true);

            $school_student= Student::hydrate($school_student);

            //$school=SchoolInfo::findOrFail(auth()->user()->school->id);

            $school_programs = Program::all()->where('school_info_id',auth()->user()->school->id);
            return view('layouts.backend.dashboard.dashboard', compact('school_student','school_programs'));
        }

        if(auth()->user()->role_id==4 && auth()->user()->status==1){
            $supervisor=Supervisor::findOrFail(auth()->user()->supervisor->id);

            return view('layouts.backend.dashboard.dashboard', compact('supervisor'));
        }


        elseif(auth()->user()->role_id != 1 && auth()->user()->status == 2 || auth()->user()->status == 3|| auth()->user()->status == 4 ){
            // return abort(403, 'Your account is not activate.');
            return view('layouts.backend.dashboard.not-active');
        }
    }



    // public function userManage($id){
    //     if(auth()->user()->role_id == 1){

    //         $deliveries = Delivery::where('created_by', $id)->count();
    //         $delivered = Delivery::where('created_by', $id)
    //                             ->where('delivery_status', 3)
    //                             ->count();
    //         $pending = Delivery::where('created_by', $id)
    //                             ->whereNotIn('delivery_status', [3])
    //                             ->count();

    //         $paidCount = Delivery::where('created_by', $id)
    //                             // ->where('delivery_status', 3)
    //                             ->where('paid_status', 1)
    //                             ->count();
    //         $unpaidCount = Delivery::where('created_by', $id)
    //                             // ->where('delivery_status', 3)
    //                             ->where('paid_status', 2)
    //                             ->count();
    //         $collection = Delivery::where('created_by', $id)
    //                            ->where('paid_status', 2)
    //                         //    ->whereIn('delivery_status', [2,3])
    //                            ->sum('collect_amount');

    //         $charge = Delivery::where('created_by', $id)
    //                         //    ->whereIn('delivery_status', [2,3])
    //                            ->where('paid_status', 2)
    //                            ->sum('total_charge');

    //         $unpaid = $collection - $charge;

    //         $getCharge = Delivery::where('created_by', $id)
    //                             // ->where('delivery_status', 3)
    //                             ->where('paid_status', 1)
    //                             ->sum('total_charge');

    //         $paidCollection = Delivery::where('created_by', $id)
    //                             ->where('paid_status', 1)
    //                             ->sum('collect_amount');

    //         $paidCharge = Delivery::where('created_by', $id)
    //                             ->where('paid_status', 1)
    //                             ->sum('total_charge');

    //         $paid = $paidCollection - $paidCharge;
    //         // dd($collection, $charge, $paidCollection, $paidCharge);
    //         return view('layouts.backend.merchants.manage', compact('deliveries', 'delivered', 'pending', 'charge', 'unpaid', 'paid', 'id', 'paidCount', 'unpaidCount', 'getCharge'));
    //     }
    //     return back();
    // }

}

resources/views/layouts/backend/dashboard/admin.blade.php
<div class="row">
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-warning card-header-icon">
          <div class="card-icon">
            <i class="material-icons">device_hub</i>
          </div>
          <p class="card-category" style="margin-right:20px ">Total User </p>
          <h3 class="card-title" style="margin-right:20px ">
            {{$user->count()}}
          </h3>
        </div>
        <div class="card-footer">
          <div class="stats">
            <i class="material-icons text-danger">link</i>
            <a href="javascript:;">See List</a>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-success card-header-icon">
          <div class="card-icon">
            <i class="material-icons">store</i>
          </div>
          <p class="card-category" style="margin-right:20px ">Recruiter Count</p>
          <h3 class="card-title" style="margin-right:20px ">
          {{$recruiter->count()}}
          </h3>
        </div>
        <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-danger">link</i>
              <a href="{{route('merchants.index')}}">See List</a>
            </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-info card-header-icon">
          <div class="card-icon">
            <i class="material-icons">how_to_reg</i>
          </div>
          <p class="card-category" style="margin-right:20px ">Student Count</p>
          <h3 class="card-title" style="margin-right:20px ">
            {{$student->count()}}
          </h3>
        </div>
        <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-danger">link</i>
              <a href="{{route('customers.index')}}">See List</a>
            </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-6">
      <div class="card card-stats">
        <div class="card-header card-header-danger card-header-icon">
          <div class="card-icon">
            <i class="material-icons" >admin_panel_settings</i>
          </div>
          <p class="card-category" style="margin-right:20px">Superviser Count</p>
          <h3 class="card-title" style="margin-right:20px">
            {{$supervisor->count()}}
          </h3>
        </div>
        <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-danger">link</i>
            <a href="{{route('role.index')}}">See List</a>
            </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <div class="card card-chart">
        <div class="card-header card-header-success">
          <div class="ct-chart" id="dailySalesChart"></div>
        </div>
        <div class="card-body">
          <h4 class="card-title">Student Details</h4>
          <p class="card-category">

            Total Student count: {{$student->count()}}

          </p>
          <p class="card-category">
            Student Directly Applied: {{$student->where('recruiter_id',null)->count()}}
          </p>
          <p class="card-category">
            Student Applied via Recruiter: {{$student->where('recruiter_id','!=',null)->count()}}
          </p>

        </div>
        <div class="card-footer">
          <div class="stats">
            Last Register at: <i class="material-icons">access_time</i>
            @if($student->first()==null)
            No Data Yet
            @else
            {{$student->first()->created_at->format('dS M,Y h:i:s a')}}
            @endif
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card card-chart">
        <div class="card-header card-header-warning">
          <div class="ct-chart" id="websiteViewsChart"></div>
        </div>
        <div class="card-body">
          <h4 class="card-title">Institution And Program</h4>
          <p class="card-category">Institution Count: {{$school->count()}}</p>
          <p class="card-category">Total Program: {{$program->count()}}</p>
          <p class="card-category">Total Applications on Programs:
            @php($i=0)
            @foreach($student as $stud)

              @php($i=$i+$stud->programs()->count())

            @endforeach
          {{$i}}
          </p>
        </div>
        <div class="card-footer">
          <div class="stats">
            Last Register at: <i class="material-icons">access_time</i>
            @if($school->first()==null)
            No Data Yet
            @else
           {{$school->first()->created_at->format('dS M,Y h:i:s a')}}
           @endif
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card card-chart">
        <div class="card-header card-header-danger">
          <div class="ct-chart" id="completedTasksChart"></div>
        </div>
        <div class="card-body">
          <h4 class="card-title">Applied Program Status</h4>
          <p class="card-category">
            @php($i=0)
            @foreach($student as $stud)
              @php($i=$i+$stud->programs()->where('status','Under Processing')->count())
            @endforeach
            Under Processing : {{$i}}
          </p>
          <p class="card-category">
            @php($i=0)
            @foreach($student as $stud)
              @php($i=$i+$stud->programs()->where('status','Need More Document')->count())
            @endforeach
            Need More Document: {{$i}}
          </p>
          <p class="card-category">
            @php($i=0)
            @foreach($student as $stud)
              @php($i=$i+$stud->programs()->where('status','Accepted By Institute')->count())
            @endforeach
            Accepted By Institute : {{$i}}
          </p>
          <p class="card-category">
            @php($i=0)
            @foreach($student as $stud)
              @php($i=$i+$stud->programs()->where('status','Rejected By Institute')->count())
            @endforeach
            Rejected By Institute : {{$i}}
          </p>
        </div>
        <div class="card-footer">
          <div class="stats">
            Last Accepted at: <i class="material-icons">access_time</i>
            @php($i=0)
            @php($j=0)

            @foreach($student as $stud)
            @if($stud->programs()->orderBy('updated_at','desc')->where('status','Accepted By Institute')->count()!=0)
              @php($j=$stud->programs()->orderBy('updated_at','desc')->where('status','Accepted By Institute')->first()->pivot->updated_at->format('dS M,Y h:i:s a'))

            @endif
            @if($j>$i)
              @php($i=$j)
            @endif
            @endforeach
            @if($i==0)
            No Data Yet
            @else
            {{$i}}
            @endif
          </div>
        </div>
      </div>
    </div>
  </div>

resources/views/layouts/backend/dashboard/dashboard.blade.php
@extends('layouts.backend.layouts.app')
@section('content')
    @if (auth()->user()->role_id == 1)
        @include('layouts.backend.dashboard.admin')
    @endif
    @if (auth()->user()->role_id == 2)
        @include('layouts.backend.dashboard.student')
    @endif
    @if (auth()->user()->role_id == 3)
        @include('layouts.backend.dashboard.recruiter')
    @endif
    @if (auth()->user()->role_id == 5)
        @include('layouts.backend.dashboard.school')
    @endif

    @if (auth()->user()->role_id == 4)
        @include('layouts.backend.dashboard.supervisor')
    @endif
@endsection

resources/views/layouts/backend/dashboard/not-active.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png">
    <title>Admission Network</title>
    <!-- Bootstrap Core CSS -->
    <link href="{{asset('css/not-active/bootstrap/dist/css/bootstrap.min.css')}}" rel="stylesheet">
    <!-- animation CSS -->
    <link href="{{asset('css/not-active/animate.css')}}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{{asset('css/not-active/style.css')}}" rel="stylesheet">
    <!-- color CSS -->
    <link href="{{asset('css/not-active/colors/default.css')}}" id="theme" rel="stylesheet">
      <link href="{{asset('/backend/css/material-kit.css?v=2.0.7')}}" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <!-- Preloader -->
    @if((auth()->user()->role_id==2)&&(auth()->user()->status==3))
    <div style="text-align:center; margin:200px auto; justify-content: center;align-items: center;">
        <a class="btn btn-primary btn-lg btn-round" href="{{ route('students-form.create') }}"><h3 class="title">Complete the Registration</h3></a>
        <br>
        <a style="background-color: #f44336" href="dashboard.html" class="btn btn-danger btn-rounded waves-effect waves-light m-b-40" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                 Back to home
             </a>

             <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                 @csrf
             </form>
    </div>
   
    @endif
    
    @if((auth()->user()->role_id==3)&&(auth()->user()->status==3))
    <div style="text-align:center; margin:200px auto; justify-content: center;align-items: center;">
        <a class="btn btn-primary btn-lg btn-round" href="{{ route('recruiters-form.create') }}"><h3 class="title">Complete the Registration</h3></a>
        <br>
        <a style="background-color: #f44336" href="dashboard.html" class="btn btn-danger btn-rounded waves-effect waves-light m-b-40" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                 Back to home
             </a>

             <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                 @csrf
             </form>
    </div>
           
    @endif

    @if((auth()->user()->role_id==5)&&(auth()->user()->status==3))
    <div style="text-align:center; margin:200px auto; justify-content: center;align-items: center;">
        <a class="btn btn-primary btn-lg btn-round" href="{{ route('school-form.create') }}"><h3 class="title">Complete the Registration</h3></a>
        <br>
        <a style="background-color: #f44336" href="dashboard.html" class="btn btn-danger btn-rounded waves-effect waves-light m-b-40" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                 Back to home
             </a>

             <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                 @csrf
             </form>
    </div>
           
    @endif

    @if((auth()->user()->status==2))
    <div style=" text-align:center; ">
        <div class="error-box">
            <div class="error-body text-center">
                <h3 class="text-success"><b>Congratulations</b></h3>
                <h2 style="color: #9c27b0">Your are successfully registered to <span style="color: #f44336"><b>Admission Network</b></h2>
                <h3 style="color: #f44336"><b>Please wait for Admin's approval</b></h3>


                <a style="background-color: #f44336" href="dashboard.html" class="btn btn-danger btn-rounded waves-effect waves-light m-b-40" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                 Back to home
             </a>

             <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                 @csrf
             </form>
        </div>
        </div>

    @endif

    @if((auth()->user()->status==4))
    <div style=" text-align:center; ">
        <div class="error-box">
            <div class="error-body text-center">
                <h3 class="text-success"><span style="color: #f44336"><b>Account Deactivated</b></span></h3>
                <h2 style="color: #9c27b0">Please comunicate with <span style="color: #f44336"><b>Admission Network</b></h2>
                <h3 style="color: #f44336"><b>mail address: admission-network@info.com</b></h3>


                <a style="background-color: #f44336" href="dashboard.html" class="btn btn-danger btn-rounded waves-effect waves-light m-b-40" href="{{ route('logout') }}"
                onclick="event.preventDefault();
                              document.getElementById('logout-form').submit();">
                 Back to home
             </a>

             <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                 @csrf
             </form>
        </div>
        </div>

    @endif

    <!-- jQuery -->
    <script src="../plugins/bower_components/jquery/dist/jquery.min.js"></script>
    <script src="{{asset('backend/js/material-kit.js?v=2.0.7')}}" type="text/javascript"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="bootstrap/dist/js/bootstrap.min.js"></script>
</body>

</html>