routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home');

Auth::routes();

Route::get('/registerInstitute', 'UserController@registerInstitute')->name('registerInstitute');

// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/students', 'HomeController@student')->name('student');
Route::get('/schools', 'HomeController@school')->name('school');
Route::get('/recruiters', 'HomeController@recruiter')->name('recruiter');
Route::get('/about', 'HomeController@about')->name('about');
Route::get('/contact', 'HomeController@contact')->name('contact');
Route::get('/study-destination', 'HomeController@studyDestination')->name('study-destination');
Route::post('/study-search-result', 'HomeController@studySearchResult')->name('study-search-result');
Route::get('/all-program/{id}', 'HomeController@program')->name('all-program');
Route::get('/country-details', 'HomeController@countryDetails')->name('country-details');


Route::resource('school-form', 'SchoolInfoController');

Route::post('user/storeSchool', 'UserController@storeSchool')->name('storeSchool');
Route::resource('user', 'UserController');

Route::middleware('auth')->group(function () {
    Route::group([ 'middleware' => 'student'], function() {
    });
        Route::get('student/show-profile/{id}', 'StudentController@showProfile')->name('students-form.showProfile');
        Route::put('program/apply/{id}/{student_id}', 'ProgramController@programApply')->name('program.apply');
        Route::resource('program', 'ProgramController');
        Route::get('/dashboard/school-index', 'AllusertableController@schoolIndex')->name('school.index');
        Route::get('get-school-list', 'AllusertableController@schoolList')->name('get-school-list');

        Route::resource('students-form', 'StudentController');

    Route::group([ 'middleware' => 'admin'], function() {


    });

    Route::get('get-user-list', 'AllusertableController@userList')->name('get-user-list');
    Route::get('/dashboard/allusrIndex/{role_id}', 'AllusertableController@index')->name('alluser.index');
    Route::get('get-student-list', 'AllusertableController@studentList')->name('get-student-list');
    Route::get('/dashboard/student-index', 'AllusertableController@studentIndex')->name('student.index');
    Route::get('get-recruiter-list', 'AllusertableController@recruiterList')->name('get-recruiter-list');
    Route::get('/dashboard/recruiter-index', 'AllusertableController@recruiterIndex')->name('recruiter.index');
    Route::get('get-supervisor-list', 'AllusertableController@supervisorList')->name('get-supervisor-list');
    Route::get('/dashboard/supervisor-index', 'AllusertableController@supervisorIndex')->name('supervisor1.index');

    Route::resource('supervisor', 'SupervisorController');

    Route::resource('country', 'CountryController');
    Route::get('get-country-list', 'CountryController@getAllCountry')->name('get-country-list');
    Route::post('get-country-info', 'CountryController@getCountryInfo')->name('get-country-info');

    Route::put('dashboard/allusrIndex/user-approval/{id}', 'StudentController@userApproval')->name('user.approval');
    Route::put('student-form/assign-supervisor/{id}', 'StudentController@assignSupervisor')->name('student-form.assignSupervisor');
    Route::resource('recruiters-form', 'RecruiterController');
    Route::get('program-recruiter-index/{id}', 'AllusertableController@programRecruiter')->name('programRecruiter.index');

    Route::get('get-studentRecruiter-list', 'RecruiterController@studentListForRecruiter')->name('get-studentRecruiter-list');
    Route::get('get-studentSupervisor-list', 'SupervisorController@studentListForSupervisor')->name('get-studentSupervisor-list');


    Route::get('campus-add', 'CampusController@campusAdd')->name('addcampus.index');
    Route::get('program-add', 'ProgramController@programAdd')->name('addprogram.index');
    Route::get('program/forall/{id}', 'ProgramController@showforall')->name('program.showforall');

    Route::resource('campus', 'CampusController');
    Route::resource('program', 'ProgramController');
    Route::resource('comment', 'CommentController');

    Route::put('program/apply/{id}/{student_id}', 'ProgramController@programApply')->name('program.apply');
    Route::get('/dashboard/allprogram-index/{id}', 'AllusertableController@programIndex')->name('allprogram.index');

    Route::put('program/assign-status/{id}/{student_id}', 'ProgramController@assignStatus')->name('program.assign-status');





    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');




    Route::get('manage/{id}', 'DashboardController@userManage')->name('user.manage');

    Route::get('/home-components', 'HomeController@homeComponents')->name('home-components');

    Route::resource('role', 'RoleController');

    Route::resource('merchants', 'MerchantController');
    Route::get('merchant-requests', 'MerchantController@merchantRequest')->name('merchant-requests');
    Route::get('merchant-inactive', 'MerchantController@merchantInactive')->name('merchants.inactive');
    Route::get('get-merchants-admin', 'MerchantController@getIndexAdmin')->name('get-merchants-admin');
    Route::get('merchant-active/{id}', 'MerchantController@merchantActive')->name('merchant.active');

    Route::resource('special-merchants', 'SpecialMerchantController');

    Route::resource('customers', 'CustomerController');
    Route::get('customers-requests', 'CustomerController@merchantRequest')->name('customers-requests');
    Route::get('customers-active/{id}', 'CustomerController@merchantActive')->name('customers.active');

    Route::resource('admin-services', 'ServiceController');

    Route::resource('admin-client', 'ClientController');
    Route::resource('authority-team', 'AuthorityTeamController');

    Route::resource('admin-inter-city-rates', 'InterCityRateController');
    Route::resource('admin-rate-info', 'AddRateInfoController');

    Route::resource('admin-about', 'AboutUsController');
    Route::resource('admin-about-card', 'AboutUsCardController');

    Route::resource('districts', 'DistrictController');

    Route::resource('areas', 'AreaController');



    Route::resource('deliveries', 'DeliveryController');
    Route::get('print/delivery-info/{id}', 'DeliveryController@printInfoDelivery')->name('deliveries.info.print');
    Route::get('print/pickup-info/{id}', 'DeliveryController@printInfoPickup')->name('deliveries.pickup.print');
    Route::get('deliveries-admin', 'DeliveryController@indexAdmin')->name('deliveries-admin');
    Route::get('all-deliveries-admin', 'DeliveryController@indexAll')->name('all.deliveries');
    Route::get('get-deliveries-admin', 'DeliveryController@getIndexAdmin')->name('get-deliveries-admin');
    Route::get('get-all-deliveries-admin', 'DeliveryController@getAll')->name('get-all-deliveries-admin');
    Route::post('manage-deliveries-admin', 'DeliveryController@manageDelivery')->name('manage-deliveries-admin');
    Route::post('get-delivery-info', 'DeliveryController@getDeliveryInfo')->name('get-delivery-info');
    Route::post('admin-delivered', 'DeliveryController@delivered')->name('admin.delivered');
    Route::post('admin-pickup', 'DeliveryController@pickup')->name('admin.pickup');
    Route::post('admin-cancel', 'DeliveryController@cancel')->name('admin.cancel');
    Route::post('admin-hold', 'DeliveryController@hold')->name('admin.hold');
    Route::post('admin-no-status', 'DeliveryController@noStatus')->name('admin.no.status');
    Route::post('admin-paid', 'DeliveryController@paid')->name('admin.paid');
    Route::post('admin-unpaid', 'DeliveryController@unPaid')->name('admin.unpaid');
    Route::post('deliveries-delete', 'DeliveryController@delete')->name('deliveries.delete');

    Route::get('admin-delivery-statuses', 'DeliveryController@statuses')->name('admin.statuses');

    Route::get('invoices', 'InvoiceController@index')->name('invoices.index');
    Route::get('get-invoices', 'InvoiceController@getInvoice')->name('get.invoices');
    Route::get('invoice/delete/{id}', 'InvoiceController@delete')->name('invoice.delete');
    Route::get('invoice/{id}', 'InvoiceController@show')->name('invoice.show');
    Route::post('delivery/invoice', 'InvoiceController@getInvoiceInfo')->name('delivery.invoice');
    Route::get('invoice/pdf-export/{id}', 'InvoiceController@export')->name('export.pdf');

    Route::resource('payment-requests', 'PaymentRequestsController');
    Route::get('get-payment-requests', 'PaymentRequestsController@getRequest');
    Route::post('admin.request.solve', 'PaymentRequestsController@solveRequest')->name('admin.request.solve');
    Route::post('admin.request.pending', 'PaymentRequestsController@pendingRequest')->name('admin.request.pending');

});

resources/views/layouts/frontend/forms/school-afterlogin-form.blade.php
@extends('layouts.backend.layouts.app1')    

@section('content')
@include('layouts.frontend.forms.create1-modal')
<div class="card card-login" style="background-image: url({{asset('backend/img/iStock-52037437.jpg')}});
    background-size: cover; background-position: top center; ">
<section id="s1" style="background-color:white;">

<h2 style="color: black"> Institution Info  </h2>

<form action="{{route('school-form.update',1)}}" method="POST">
    @csrf
    {{ method_field('PUT') }}
<div class="continer">

        <div class="card-body table-responsive" >
            <button type="button" class="btn btn-info btn-sm pull-right" 
              data-toggle="modal" data-target="#exampleModalLongTitle" >
              Add Campus</button>
              <div class="clearfix"></div>
        </div>
        <div class="card">
            <div class="card-header card-header-info card-header-icon">
              
              <h4 class="card-title"><b>List of Campus</b></h4>
            </div>
        <div class="table-responsive">
            <table class="table">
                <thead class="card-header-info">
                  <tr style="text-align: center" >
                    <th scope="col">SL</th>
                    <th scope="col" >Address</th>
                    <th scope="col" >Zip</th>
                    <th scope="col" >City</th>
                    <th scope="col" >State</th>
                    <th scope="col"  >Country</th>
                    <th scope="col"  >Action</th>
                  </tr>
                </thead>
                <tbody>
                    @php
                    $i = 1
                    @endphp
             @foreach ($campuses as $campus) 
                
                    <tr style="text-align: center" >
                        <td>{{$i++}}</td>
                        <td>{{$campus->address}}</td>
                        <td>{{$campus->zip}}</td>
                        <td>{{$campus->city}}</td>                        
                        <td>{{$campus->state}}</td>
                        <td>{{$campus->country}}</td>
                        <td class="td-actions">1
                            {{-- <a class="btn btn-primary btn-link" href="{{ route('admin-client.edit', $row->id) }}">
                                <i class="material-icons">edit</i>
                            </a>

                            <form class="form-delete" action="{{ route('admin-client.destroy', $row->id) }}" method="POST">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <button type="submit" title="Delete" class="delete btn btn-danger btn-link">
                                    <i class="material-icons">close</i>
                                  </button>
                            </form> --}}


                          </td>
                    </tr>
            @endforeach
                  </tr>
                </tbody>
              </table>
            </div>
        </div>


            

            <div class="card-body table-responsive" >
                <button type="button" class="btn btn-warning btn-sm pull-right" 
                  data-toggle="modal" data-target="#exampleModalLongTitle1" >
                  Add Program</button>
                  <div class="clearfix"></div>
            </div>  
            <h4><b>List of Courses</b></h4>
            {{-- <div class="table-responsive">
            <table class="table table-bordered table-hover" data-form="deleteForm">
                <thead class="card-header-primary" style="background-color: slateblue; color:white;">
                  <tr style="text-align: center">
                    <th scope="col">SL</th>
                    <th scope="col">Course Name</th>
                    <th scope="col">Programe Level</th>
                    <th scope="col">Intakes</th>
                    <th scope="col">Course Duration</th>
                    <th scope="col">Seasons</th>
                    <th scope="col">Tution Free</th>
                    <th scope="col">Admission Free</th>
                    <th scope="col">Language Profeciency(English)</th>
                    <th scope="col">Required English Exam Type</th>
                    <th scope="col">Visa Type Required </th>
                    <th scope="col">Required Grading Scheme</th>
                    <th scope="col">Required Grade Scale*(out of)</th>
                    <th scope="col">Required Grade Average</th>
                  </tr>
                </thead>
                <tbody>
                    @foreach ($programs as $program) 
                    <tr style="text-align: center" >
                        <td>{{$i++}}</td>
                        <td>{{$program->course_name}}</td>
                        <td>{{$program->programe_level}}</td>
                        <td>{{$program->intakes}}</td>
                        <td>{{$program->course_duration}}</td>                       
                        <td>{{$program->seasons}}</td>
                        <td>{{$program->tution_free}}</td>
                        <td>{{$program->admission_free}}</td>
                        <td>{{$program->language_profeciency}}</td>
                        <td>{{$program->required_exam_type}}</td>
                        <td>{{$program->required_visa_type}}</td>
                        <td>{{$program->required_grading_scheme}}</td>
                        <td>{{$program->required_grade_scale}}</td>
                        <td>{{$program->required_grade_avg}}</td>
                      
                    </tr>
               @endforeach
                </tbody>
              </table>
            </div> --}}


            <div class="container-fluid content-row">
                <div class="row">
                    <div class="col-sm-12">
                        @foreach ($programs as $program) 
                        <div class="card card-nav-tabs">
                            <div class="card-header card-header-warning">
                                <span class="material-icons">
                                    school<h4>Course: {{$program->course_name}} </h4>
                                    </span>
                                    
                            </div>
                            <div class="card-body">
                              
                              <div class="table-responsive">
                                <table class="table" style="table-layout: fixed">
                                  
                                  <tbody>
                                    <tr>
                                        
                                      </tr>
                                    <tr>
                                      <th>Programe Level</th>
                                      <td>{{$program->programe_level}}</td>
                                    
                                        <th>Intakes</th>
                                        <td>{{$program->intakes}}</td>
                                      </tr>
                                      <tr>
                                        <th>Course Duration</th>
                                        <td>{{$program->course_duration}}</td>
                                     
                                        <th>Tution Free</th>
                                        <td>{{$program->tution_free}}</td>
                                      </tr>
                                      <tr>
                                        <th>Admission Free</th>
                                        <td>{{$program->admission_free}}</td>
                                        <th>Language Profeciency(English)</th>
                                        <td>{{$program->language_profeciency}}</td>
                                      </tr>
                                    <tr>

                                        <td colspan="4" class="td-actions">
                                            <button type="button" rel="tooltip" class="btn btn-danger" data-original-title="" title="">
                                              <i class="material-icons">close</i>
                                            </button>
                                        </td>
                                      </tr>
                                    
                                  </tbody>
                                </table>
                              </div>
                          
                            </div>
                          </div>
                          @endforeach
                    </div> 
                </div>
            </div>

            <div class="row">
       
        <div class="col-md-6">
            <div class="input-group" style="margin-top:15px;">
                <select class="role form-control @error('institution_type') is-invalid @enderror"
                name="institution_type" required>
                   <option>Select Institution</option>
                   {{-- <option value="4">Customer</option> --}}
                   <option value="1">University</option>
                   <option value="2">High School</option>
                   <option value="3">College</option>
                   <option value="4">English Istitute</option>
               </select>
               @error('institution_type')
                   <span class="invalid-feedback" role="alert">
                       <strong>{{ $message }}</strong>
                   </span>
               @enderror
            </div>
        </div>

        <div class="col-md-6">
            <div class="input-group">
                <input id="no_of_campus" type="no_of_campus" placeholder="Number Of Campus"
                    class="form-control @error('no_of_campus') 
                    is-invalid @enderror" name="no_of_campus"
                    value="{{ old('no_of_campus') }}" requir autocomplete="no_of_campus">

                @error('no_of_campus')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
    </div>

    <div class="row" style="margin-top:15px;">

        <div class="col-md-6">
            <div class="input-group">
                <label class="from-control header 6" 
                    style="margin-top:15px; color:black;font-size:16px;font-wieght:18px">
                    Upload Logo of the Institution : </label>
            </div>
        </div>
        <div class="col-md-6">

            <input class="form-control 
                    @error('logo_name') is-invalid @enderror" type="file" name="logo_name"
                requir>
            @error('logo_name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror

        </div>

    </div>
    

    <div class="row">

        <div class="col-md-6">
            <div class="input-group">
                <label class="from-control header 6"
                        style="margin-top:15px; color:black;font-size:16px;font-wieght:18px">
                    Upload Business Certificate : </label>
            </div>
        </div>
        <div class="col-md-6">

            <input class="form-control 
                    @error('certificate') is-invalid @enderror" type="file" name="certificate"
                requir>
            @error('certificate')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
        </div>

    </div>


            

      </div>

      <button type="submit" class="btn btn-info" > Completec Registration</button>
    </form>
</section>
</div>

@endsection

resources/views/layouts/frontend/forms/school-form.blade.php
<form action="{{route('storeSchool')}}" method="POST">
    @csrf
    <div class="row">
        <div style="padding: 15px" class="col-md-12">
            <div class="form-group">
                <label class="required" for="country">Destination Country</label>
                {{ Form::select('country_code', countries() ? ['' => '-- Select --']+countries() : [], null, ['class' => 'form-control', 'id' => 'country']) }}
            </div>
        </div>
    </div>

    <div class="row">
        <div style="padding: 15px" class="col-md-12">
            <div class="form-group">
                <label class="required" for="school">School Name</label>
                <input id="school_name" type="text"
                class="form-control @error('school_name') is-invalid @enderror"
                name="school_name" value="{{ old('school_name') }}"
                required autocomplete="school_name" autofocus>

                            @error('school_name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
            </div>
        </div>
    </div>

    <div class="row">
        <div style="padding: 15px" class="col-md-6">
            <div class="form-group">
                <label class="required" for="first_name">Contact First Name</label>
                <input type="text" class="form-control" id="first_name"
                        name=contact_first_name>
            </div>
        </div>

        <div style="padding: 15px" class="col-md-6">
            <div class="form-group">
                <label class="required" for="last_name">Contact Last Name</label>
                <input type="text" class="form-control" id="last_name"
                 name=contact_last_name>
            </div>
        </div>
    </div>

    <div class="row">
        <div style="padding: 15px" class="col-md-6">
            <div class="form-group">
                <label class="required" for="email">Contact Email</label>
                <input id="contact_email" type="text"
                class="form-control @error('contact_email') is-invalid @enderror"
                name="contact_email" value="{{ old('contact_email') }}"
                required autocomplete="contact_email" autofocus>

                            @error('contact_email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
            </div>
        </div>

        <div style="padding: 15px" class="col-md-6">
            <div class="form-group">
                <label for="number">Phone Number</label>
                <input id="contact_number" type="text"
                class="form-control @error('contact_number') is-invalid @enderror"
                name="contact_number" value="{{ old('contact_number') }}"
                required autocomplete="contact_number" autofocus>

                            @error('contact_number')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
            </div>
        </div>
    </div>

    <div class="row">
        <div style="padding: 15px" class="col-md-12">
            <div class="form-group">
                <label class="required" for="c_title">Contact Title</label>
                <input type="text" class="form-control" id="c_title" name="contact_title">
            </div>
        </div>
    </div>

    <div class="row">
        <div style="padding: 15px" class="col-md-12">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" onclick="myFunction()" >
                <label class="form-check-label" for="defaultCheck1">
                    Check if you have been referred by someone in Admission Network
                </label>
            </div>
        </div>
    </div>

    <div id="myDIV" style="display:none">
        <div class="row">
            <div style="padding: 15px" class="col-md-12">
                <div class="form-group">
                    <label class="required" for="r_c_title">Contact full name</label>
                    <input type="text" class="form-control" id="r_c_title" name="ref_name">
                </div>
            </div>
        </div>

        <div class="row">
            <div style="padding: 15px" class="col-md-12">
                <div class="form-group">
                    <label class="required" for="r_email">Contact Email</label>
                    <input type="email" class="form-control" id="ref_email">
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div style="padding: 15px" class="col-md-6">
            <div class="form-group">

                <input id="password" type="password"
                placeholder="Enter Password"
                class="form-control @error('password') is-invalid @enderror"
                name="password" required autocomplete="new-password">

                @error('password')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div style="padding: 15px" class="col-md-6">
            <div class="form-group">
                <div class="input-group-prepend">

                <input id="password-confirm" type="password"
                placeholder="Confirm Password"  class="form-control @error('password-confirm') is-invalid @enderror"
                name="password-confirm" required autocomplete="new-password">

                @error('password-confirm')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
            <span id='message'></span>
            </div>
        </div>
        </div>

    <div class="row">
        <div style="padding: 15px" class="col-md-12">
            <div class="form-group">
                <label for="textarea">Any additional comments:</label>
                <textarea class="form-control" id="textarea" rows="3" name="comment"></textarea>
              </div>
        </div>
    </div>

    <p>
        Admission Network is committed to protecting and respecting your privacy, and we’ll only use your personal information to administer your account and to provide the products and services you requested from us. From time to time, we would like to contact you about our products and services, as well as other content that may be of interest to you. If you consent to us contacting you for this purpose, please tick below to say how you would like us to contact you:
    </p>
    <div class="row">
        <div style="padding: 15px" class="col-md-12">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="agree" name="agree_communication">
                <label class="form-check-label" for="agree">
                    I agree to receive other communications from Admission Network.
                </label>
            </div>
        </div>
    </div>


    <p>
        You can unsubscribe from these communications at any time. For more information on how to unsubscribe, our privacy practices, and how we are committed to protecting and respecting your privacy, please review our Privacy Policy.
    </p>
    <p>
        By clicking submit below, you consent to allow Admission Network to store and process the personal information submitted above to provide you the content requested.
    </p>

    @if(auth()->user()== null)
        <button style="color: #808080; background-color: #fff; border-color: #fff" type="submit" class="btn btn-success btn-lg" id="testing1" >Submit</button>
    @else
        <button style="color: #808080; background-color: #fff; border-color: #fff" type="submit" class="btn btn-success btn-lg" id="testing1" disabled>Can not register institute while loged in</button>
@endif
</form>